### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by gyc123456-1** [BillXuce/wqxt_pdf_maker#1]
Traceback (most recent call last):
  File "L:\wqxt_pdf_maker-master\main_pdf.py", line 25, in <module>
    pdfmaker.addBookMarks()
  File "L:\wqxt_pdf_maker-master\pdfmaker.py", line 29, in addBookMarks
    doc = fitz.open( tempPath );
  File "C:\Users\yc\AppData\Local\Programs\Python\Python38\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '1.pdf'

**Comment by gyc123456-1** [comment]
c，没想到都一年多了

**Comment by BillXuce** [comment]
> c，没想到都一年多了

这项目都荒废3年了

**Comment by gyc123456-1** [comment]
> > c，没想到都一年多了
> 
> 这项目都荒废3年了

你不回我都以为你原地趋势了（bushi
